### ISSUE TITLE
No Increase

### ISSUE THREAD

**Issue by aslisk** [DevelopersWork/Stream-Botter#1]
It just stays like this viewers not increase [tried keep it open 30 minutes]

![image](https://user-images.githubusercontent.com/28812980/154811467-e8162b9b-c6d7-4526-b79d-0b15f6c52459.png)

**Comment by aslisk** [comment]
it should show video title and link in terminal

**Comment by DevelopersWork** [comment]
> it should show video title and link in terminal

it will be shown if there is title and link in the html response
