### ISSUE TITLE
Very slow increase in viewers on the stream

### ISSUE THREAD

**Issue by villiam1999** [DevelopersWork/Stream-Botter#2]
in 40 minutes for only 20 successful bots. In addition, when there are 12 viewers on a live broadcast, there are already 20 successful bots.
![изображение_2022-02-23_233154](https://user-images.githubusercontent.com/100228538/155403333-8798a373-46e2-46d4-addc-2c730307e5cb.png)

**Comment by DevelopersWork** [comment]
`in 40 minutes for only 20 successful bots` -> Bot currently has slow phase only. I've added new parameter **SPEED** this will control the speed of the bot now. Increase its value if you want more speed.
`when there are 12 viewers on a live broadcast, there are already 20 successful bots.` -> If you observe the watching in the console it says **9**. Cause YouTube will take a while before updating its count. The count in console only updates where there is successful request to youtube

Caution: Proxies maybe getting banned by the youtube if they are used must faster.
