### ISSUE TITLE
not working after todays update

### ISSUE THREAD

**Issue by aslisk** [DevelopersWork/Stream-Botter#3]
Not Working after todays update

im trying 

python3 main.py 500 abcdefg 10

**Comment by DevelopersWork** [comment]
@aslik currently I am looking into it. Trying find an optimal way so we wont get proxies banned

**Comment by aslisk** [comment]
https://prnt.sc/V8_z6rqGsQEK

**Comment by DevelopersWork** [comment]
Working now...
![image](https://user-images.githubusercontent.com/17892671/155660352-8aea1adb-f7a0-4647-96ad-9d0927b8dad1.png)

Maybe from next update I will use feature branch to test my changes....

**Comment by aslisk** [comment]
add cookie container. look in  it may help, https://github.com/Airkek/Youtube-Viewers/issues/132

**Comment by DevelopersWork** [comment]
> add cookie container. look in it may help, [Airkek/Youtube-Viewers#132](https://github.com/Airkek/Youtube-Viewers/issues/132)

sure will check it
