### ISSUE TITLE
was better

### ISSUE THREAD

**Issue by aslisk** [DevelopersWork/Stream-Botter#4]
it was working better yesterday. i was able to get 100+ viewers but after todays update not even able to get 20 viewers max getting 10-15 viewers

**Comment by DevelopersWork** [comment]
It's because of the free proxies. I'm checking if I do something about these. Will update once the code is ready

**Comment by DevelopersWork** [comment]
I really appreciate your interest on my work. 
![image](https://user-images.githubusercontent.com/17892671/155784267-4e57ed1e-0c8b-448f-8f1b-f25e41ea6eef.png)
The updated code is showing results as expected. Phew***

I would like to clarify one thing: views are not increased by the bot. Only watching will be, cause youtube detects this is a bot and removes in post processing
