### ISSUE TITLE
It's working slowly again

### ISSUE THREAD

**Issue by villiam1999** [DevelopersWork/Stream-Botter#5]
As always, in 40 minutes there were even fewer views (3), although I have a speed of 10
![изображение_2022-02-25_153421](https://user-images.githubusercontent.com/100228538/155715968-774eb43e-3c75-4c08-83e3-8cc73744ec28.png)

**Comment by villiam1999** [comment]
Okay, just here the user wrote that in the previous version of your program he could gain 100 viewers, good luck to you

**Comment by DevelopersWork** [comment]
I really appreciate your interest on my work. 
![image](https://user-images.githubusercontent.com/17892671/155784267-4e57ed1e-0c8b-448f-8f1b-f25e41ea6eef.png)
The updated code is showing results as expected. Phew***
